/**
 * The demo dataset, as data.
 *
 * Pure and deterministic: no I/O, no `node:` imports, no `Date.now()`, no
 * `Math.random()`. Everything comes from the caller's `now` and a fixed-seed
 * PRNG, so the same arguments produce byte-identical rows on any machine —
 * which is what makes the screenshots in `docs/screenshots/` reproducible
 * rather than a snapshot of one afternoon's luck.
 *
 * Purity is also why this file is a sibling of `seed-demo.mjs` rather than
 * part of it: `test/demo-seed.test.ts` imports it inside `workerd`, inserts
 * what it returns into a real D1, and runs the real rollup and the real
 * dashboard queries over the result. A generator that reached for the
 * filesystem or a subprocess could not be tested that way.
 *
 * ## Why this writes rows instead of firing requests
 *
 * `e2e/seed.ts` deliberately builds its fixtures through the public HTTP API,
 * which makes it a test of that API. It also documents the two things that
 * approach provably cannot vary (its own module comment): `request.cf` is
 * fetched once per `wrangler dev` process, so every click carries the same
 * country, and a click's timestamp is computed inside the Worker, so every
 * click lands today. One country and one day are exactly the two axes a
 * screenshot of a world map and a 180-day chart needs.
 *
 * So this generator is the other half of the pair, with the opposite
 * trade-off stated plainly: it fabricates rows, it is not a test of the
 * ingestion path, and it must therefore keep its column set in step with
 * `src/db/clicks.ts` by hand. `test/demo-seed.test.ts` pins that in both
 * directions so "by hand" means "with a failing test when it drifts", the
 * same guard `test/compliance.test.ts` puts on the data map.
 */

/** Seconds in a day, named because it appears in date arithmetic throughout. */
const DAY = 86_400;

/**
 * mulberry32 — 32 bits of state, uniform enough for sampling weighted pools
 * and small enough to read. Not for anything that needs to be unguessable:
 * this file never produces a secret, and the one real password in the dataset
 * is a literal (`DEMO_PASSWORD`) precisely so nobody mistakes generated bytes
 * for entropy.
 */
function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4_294_967_296;
  };
}

/** The password on the one protected link, so a reader can actually open the
 *  interstitial the screenshot shows. Public on purpose; the seed only ever
 *  runs against a local database. */
export const DEMO_PASSWORD = "open-sesame";

const TAGS = [
  { id: 1, name: "Product", color: "#3987e5" },
  { id: 2, name: "Campaign", color: "#d95926" },
  { id: 3, name: "Docs", color: "#199e70" },
  { id: 4, name: "Social", color: "#d55181" },
  { id: 5, name: "Newsletter", color: "#9085e9" },
  { id: 6, name: "Events", color: "#c98500" },
];

/**
 * Somewhere for a visitor to be.
 *
 * `weight` is a share of all traffic, and the shape of it — Italy first, then
 * the rest of Europe, then the Americas and Asia — is the audience a
 * European open-source project actually has. A uniform world would render a
 * choropleth with nothing to say.
 *
 * Every field here is one Cloudflare fills in on `request.cf`
 * (`src/lib/request-context.ts` reads exactly these), so a row from this
 * generator and a row from a real click are the same shape: `colo` is a real
 * airport code for a datacenter near the city, `asnOrg` a real carrier in
 * that market, `timezone` the IANA zone the city is actually in.
 */
const PLACES = [
  {
    weight: 210,
    continent: "EU",
    country: "IT",
    region: "Lombardy",
    city: "Milan",
    timezone: "Europe/Rome",
    colo: "MXP",
    asnOrg: "Vodafone Italia",
    language: "it-IT",
  },
  {
    weight: 120,
    continent: "EU",
    country: "IT",
    region: "Lazio",
    city: "Rome",
    timezone: "Europe/Rome",
    colo: "FCO",
    asnOrg: "Telecom Italia",
    language: "it-IT",
  },
  {
    weight: 55,
    continent: "EU",
    country: "IT",
    region: "Piedmont",
    city: "Turin",
    timezone: "Europe/Rome",
    colo: "MXP",
    asnOrg: "Fastweb",
    language: "it-IT",
  },
  {
    weight: 48,
    continent: "EU",
    country: "IT",
    region: "Emilia-Romagna",
    city: "Bologna",
    timezone: "Europe/Rome",
    colo: "MXP",
    asnOrg: "WindTre",
    language: "it-IT",
  },
  {
    weight: 96,
    continent: "NA",
    country: "US",
    region: "California",
    city: "San Francisco",
    timezone: "America/Los_Angeles",
    colo: "SJC",
    asnOrg: "Comcast Cable",
    language: "en-US",
  },
  {
    weight: 74,
    continent: "NA",
    country: "US",
    region: "New York",
    city: "New York",
    timezone: "America/New_York",
    colo: "EWR",
    asnOrg: "Verizon Fios",
    language: "en-US",
  },
  {
    weight: 40,
    continent: "NA",
    country: "US",
    region: "Texas",
    city: "Austin",
    timezone: "America/Chicago",
    colo: "DFW",
    asnOrg: "AT&T Internet",
    language: "en-US",
  },
  {
    weight: 88,
    continent: "EU",
    country: "DE",
    region: "Berlin",
    city: "Berlin",
    timezone: "Europe/Berlin",
    colo: "TXL",
    asnOrg: "Deutsche Telekom",
    language: "de-DE",
  },
  {
    weight: 44,
    continent: "EU",
    country: "DE",
    region: "Bavaria",
    city: "Munich",
    timezone: "Europe/Berlin",
    colo: "MUC",
    asnOrg: "Vodafone Germany",
    language: "de-DE",
  },
  {
    weight: 70,
    continent: "EU",
    country: "FR",
    region: "Île-de-France",
    city: "Paris",
    timezone: "Europe/Paris",
    colo: "CDG",
    asnOrg: "Orange",
    language: "fr-FR",
  },
  {
    weight: 66,
    continent: "EU",
    country: "GB",
    region: "England",
    city: "London",
    timezone: "Europe/London",
    colo: "LHR",
    asnOrg: "BT",
    language: "en-GB",
  },
  {
    weight: 42,
    continent: "EU",
    country: "ES",
    region: "Madrid",
    city: "Madrid",
    timezone: "Europe/Madrid",
    colo: "MAD",
    asnOrg: "Telefonica de España",
    language: "es-ES",
  },
  {
    weight: 38,
    continent: "EU",
    country: "NL",
    region: "North Holland",
    city: "Amsterdam",
    timezone: "Europe/Amsterdam",
    colo: "AMS",
    asnOrg: "KPN",
    language: "nl-NL",
  },
  {
    weight: 26,
    continent: "EU",
    country: "CH",
    region: "Zurich",
    city: "Zurich",
    timezone: "Europe/Zurich",
    colo: "ZRH",
    asnOrg: "Swisscom",
    language: "de-CH",
  },
  {
    weight: 24,
    continent: "EU",
    country: "AT",
    region: "Vienna",
    city: "Vienna",
    timezone: "Europe/Vienna",
    colo: "VIE",
    asnOrg: "A1 Telekom Austria",
    language: "de-AT",
  },
  {
    weight: 30,
    continent: "EU",
    country: "PL",
    region: "Masovia",
    city: "Warsaw",
    timezone: "Europe/Warsaw",
    colo: "WAW",
    asnOrg: "Orange Polska",
    language: "pl-PL",
  },
  {
    weight: 22,
    continent: "EU",
    country: "SE",
    region: "Stockholm",
    city: "Stockholm",
    timezone: "Europe/Stockholm",
    colo: "ARN",
    asnOrg: "Telia",
    language: "sv-SE",
  },
  {
    weight: 20,
    continent: "EU",
    country: "PT",
    region: "Lisbon",
    city: "Lisbon",
    timezone: "Europe/Lisbon",
    colo: "LIS",
    asnOrg: "MEO",
    language: "pt-PT",
  },
  {
    weight: 18,
    continent: "EU",
    country: "IE",
    region: "Leinster",
    city: "Dublin",
    timezone: "Europe/Dublin",
    colo: "DUB",
    asnOrg: "Eir",
    language: "en-IE",
  },
  {
    weight: 16,
    continent: "EU",
    country: "GR",
    region: "Attica",
    city: "Athens",
    timezone: "Europe/Athens",
    colo: "ATH",
    asnOrg: "OTE",
    language: "el-GR",
  },
  {
    weight: 34,
    continent: "SA",
    country: "BR",
    region: "São Paulo",
    city: "São Paulo",
    timezone: "America/Sao_Paulo",
    colo: "GRU",
    asnOrg: "Vivo Fibra",
    language: "pt-BR",
  },
  {
    weight: 32,
    continent: "AS",
    country: "IN",
    region: "Maharashtra",
    city: "Mumbai",
    timezone: "Asia/Kolkata",
    colo: "BOM",
    asnOrg: "Jio",
    language: "en-IN",
  },
  {
    weight: 24,
    continent: "AS",
    country: "JP",
    region: "Tokyo",
    city: "Tokyo",
    timezone: "Asia/Tokyo",
    colo: "NRT",
    asnOrg: "NTT Communications",
    language: "ja-JP",
  },
  {
    weight: 26,
    continent: "NA",
    country: "CA",
    region: "Ontario",
    city: "Toronto",
    timezone: "America/Toronto",
    colo: "YYZ",
    asnOrg: "Rogers Communications",
    language: "en-CA",
  },
  {
    weight: 20,
    continent: "OC",
    country: "AU",
    region: "New South Wales",
    city: "Sydney",
    timezone: "Australia/Sydney",
    colo: "SYD",
    asnOrg: "Telstra",
    language: "en-AU",
  },
  {
    weight: 14,
    continent: "AF",
    country: "ZA",
    region: "Gauteng",
    city: "Johannesburg",
    timezone: "Africa/Johannesburg",
    colo: "JNB",
    asnOrg: "Vodacom",
    language: "en-ZA",
  },
];

/**
 * Device, OS and browser travel together — a Safari on Windows or an iOS 18
 * on a desktop would be visible nonsense in three panels at once, because the
 * dashboard breaks all three out separately from the same row. So they are
 * sampled as one combination rather than three independent draws.
 *
 * `bot: true` entries mirror what `src/lib/ua.ts` actually stores for a
 * crawler: `device_type = "bot"` and null everywhere else, which the rollup
 * then aggregates as the literal `"unknown"`.
 */
const CLIENTS = [
  {
    weight: 150,
    deviceType: "desktop",
    os: "macOS",
    osVersion: "26.1",
    browser: "Chrome",
    browserVersion: "141.0.0.0",
  },
  {
    weight: 96,
    deviceType: "desktop",
    os: "macOS",
    osVersion: "26.1",
    browser: "Safari",
    browserVersion: "26.1",
  },
  {
    weight: 128,
    deviceType: "desktop",
    os: "Windows",
    osVersion: "11",
    browser: "Chrome",
    browserVersion: "141.0.0.0",
  },
  {
    weight: 44,
    deviceType: "desktop",
    os: "Windows",
    osVersion: "11",
    browser: "Edge",
    browserVersion: "141.0.3537.57",
  },
  {
    weight: 30,
    deviceType: "desktop",
    os: "Linux",
    osVersion: null,
    browser: "Firefox",
    browserVersion: "146.0",
  },
  {
    weight: 22,
    deviceType: "desktop",
    os: "Linux",
    osVersion: null,
    browser: "Chrome",
    browserVersion: "141.0.0.0",
  },
  {
    weight: 172,
    deviceType: "mobile",
    os: "iOS",
    osVersion: "26.1",
    browser: "Safari",
    browserVersion: "26.1",
  },
  {
    weight: 58,
    deviceType: "mobile",
    os: "iOS",
    osVersion: "26.1",
    browser: "Chrome",
    browserVersion: "141.0.7390.76",
  },
  {
    weight: 130,
    deviceType: "mobile",
    os: "Android",
    osVersion: "16",
    browser: "Chrome",
    browserVersion: "141.0.0.0",
  },
  {
    weight: 26,
    deviceType: "mobile",
    os: "Android",
    osVersion: "16",
    browser: "Samsung Internet",
    browserVersion: "28.0",
  },
  {
    weight: 34,
    deviceType: "tablet",
    os: "iPadOS",
    osVersion: "26.1",
    browser: "Safari",
    browserVersion: "26.1",
  },
  {
    weight: 10,
    deviceType: "tablet",
    os: "Android",
    osVersion: "16",
    browser: "Chrome",
    browserVersion: "141.0.0.0",
  },
  {
    weight: 26,
    deviceType: "bot",
    os: null,
    osVersion: null,
    browser: null,
    browserVersion: null,
    bot: true,
  },
];

/**
 * Where a click came from. `type` is not sampled independently of `host`: it
 * is what `src/lib/referrer.ts` would classify that host as, so the Channels
 * panel and the Referrers panel always agree. `direct` carries a null host,
 * exactly as a request with no `Referer` header does.
 */
const REFERRERS = [
  { weight: 300, host: null, type: "direct" },
  { weight: 74, host: "google.com", type: "search" },
  { weight: 20, host: "duckduckgo.com", type: "search" },
  { weight: 14, host: "bing.com", type: "search" },
  { weight: 60, host: "x.com", type: "social" },
  { weight: 40, host: "linkedin.com", type: "social" },
  { weight: 34, host: "reddit.com", type: "social" },
  { weight: 22, host: "t.me", type: "social" },
  { weight: 16, host: "youtube.com", type: "social" },
  { weight: 34, host: "chatgpt.com", type: "ai" },
  { weight: 26, host: "claude.ai", type: "ai" },
  { weight: 14, host: "perplexity.ai", type: "ai" },
  { weight: 40, host: "mail.google.com", type: "email" },
  { weight: 18, host: "outlook.office.com", type: "email" },
  { weight: 30, host: "news.ycombinator.com", type: "other" },
  { weight: 20, host: "lobste.rs", type: "other" },
  { weight: 14, host: "dev.to", type: "other" },
];

/**
 * A day's shape, in relative weight per UTC hour.
 *
 * Two humps rather than one: European office hours peak around 08:00–10:00
 * UTC, the American morning arrives around 15:00–17:00 UTC, and the trough
 * between 01:00 and 05:00 UTC never quite reaches zero because the audience
 * spans enough longitude. The hour-by-weekday heatmap on the link detail page
 * is drawing this array, so a flat one would produce a flat heatmap — the one
 * chart in the product that exists to show a shape.
 */
const HOUR_WEIGHTS = [
  18, 12, 9, 8, 9, 14, 26, 48, 78, 96, 92, 84, 76, 82, 94, 104, 98, 86, 72, 62, 54, 44, 34, 24,
];

/** Monday is 1 in `Date#getUTCDay`; the weekend is the quiet pair. Traffic on
 *  a Sunday is roughly half a Wednesday's, which is what makes the 90-day
 *  time series look like a comb rather than a smear. */
const WEEKDAY_WEIGHTS = [0.55, 1.0, 1.08, 1.06, 1.02, 0.92, 0.6];

/**
 * The links, and how each one behaves.
 *
 * `weight` is a share of the daily total; `shape` bends that share over the
 * link's own life. Together they give the Top Links panel a real ordering and
 * the time series a real story rather than sixteen parallel lines.
 *
 * The moments in a link's life — `startAt`, `expiresAt`, `inactiveFrom`,
 * `deletedAt` — are **fractions of the window**, not day numbers. A link that
 * appeared on day 96 of 180 is a link that appeared 53% of the way through,
 * and `--days 30` should tell the same story compressed rather than dropping
 * every link whose day number fell off the end. (It did drop them, the first
 * time this was written with absolute day numbers: `--days 5` produced four
 * links and an empty dashboard.)
 */
const LINKS = [
  {
    id: 1,
    slug: "launch",
    targetUrl: "https://github.com/amargiovanni/margiolink/releases/tag/v1.0.0",
    title: "MargioLink 1.0",
    description: "Release announcement — the post that started it.",
    tagIds: [1, 2],
    startAt: 0,
    weight: 26,
    // A launch is a spike that decays: most of a release post's traffic
    // arrives in its first fortnight and never comes back.
    shape: (t) => 0.22 + 2.6 * Math.exp(-t * 9),
    channels: { social: 2.4, other: 2.2, ai: 0.6 },
    utm: null,
  },
  {
    id: 2,
    slug: "docs",
    targetUrl: "https://github.com/amargiovanni/margiolink#readme",
    title: "Documentation",
    description: "The README, wherever it lives this week.",
    tagIds: [3],
    startAt: 0,
    weight: 22,
    // Documentation is the opposite: it accrues. Search and AI assistants
    // find it months later, which is why its channel mix leans that way.
    shape: (t) => 0.4 + 1.5 * t,
    channels: { search: 2.6, ai: 2.4, direct: 1.2 },
    utm: null,
  },
  {
    id: 3,
    slug: "privacy-first",
    targetUrl:
      "https://github.com/amargiovanni/margiolink/blob/main/README.md#how-the-privacy-design-works",
    title: "Analytics without an IP address",
    description: "How the visitor hash works, and what it deliberately cannot do.",
    tagIds: [1, 3],
    startAt: 0.07,
    weight: 19,
    shape: (t) => 0.3 + 1.9 * Math.sqrt(t),
    channels: { search: 2.2, ai: 2.8, social: 1.4 },
    utm: null,
  },
  {
    id: 4,
    slug: "newsletter-sep",
    targetUrl: "https://github.com/amargiovanni/margiolink/blob/main/CHANGELOG.md",
    title: "September newsletter — what shipped",
    description: "Single link in the monthly mail-out.",
    tagIds: [5, 2],
    startAt: 0.53,
    weight: 14,
    // A newsletter is a send, not a trend: one enormous day, a tail of a
    // week, then nothing.
    shape: (t) => 0.06 + 5.0 * Math.exp(-t * 26),
    channels: { email: 22, direct: 1.4 },
    utm: {
      source: "newsletter",
      medium: "email",
      campaign: "september-digest",
      content: "hero-button",
      term: null,
    },
  },
  {
    id: 5,
    slug: "qr-poster",
    targetUrl: "https://github.com/amargiovanni/margiolink",
    title: "Conference poster QR",
    description: "Printed on the stand at the September meetup.",
    tagIds: [6],
    startAt: 0.6,
    weight: 9,
    shape: (t) => 0.1 + 3.4 * Math.exp(-t * 12),
    channels: { direct: 40 },
    // The one link where most traffic arrives with `?s=qr`, so the Scans vs
    // clicks panel on its detail page has both bars.
    qrShare: 0.86,
    mobileBias: 3.2,
    utm: {
      source: "poster",
      medium: "qr",
      campaign: "devfest-milano",
      content: null,
      term: null,
    },
  },
  {
    id: 6,
    slug: "webinar",
    targetUrl: "https://example.com/webinar/registration",
    title: "Webinar — self-hosting on Cloudflare",
    description: "Registration closed; the link now points at the recording.",
    tagIds: [6, 2],
    startAt: 0.22,
    weight: 8,
    shape: (t) => 0.2 + 2.2 * Math.exp(-t * 7),
    channels: { email: 3.0, social: 1.6 },
    // Expiry lands inside the window, so the Outcomes panel shows the switch
    // from `redirect` to `expired` actually happening rather than a link that
    // was always dead.
    expiresAt: 0.71,
    expiredUrl: "https://example.com/webinar/recording",
    utm: {
      source: "mailing",
      medium: "email",
      campaign: "cloudflare-webinar",
      content: null,
      term: null,
    },
  },
  {
    id: 7,
    slug: "beta-invite",
    targetUrl: "https://example.com/beta/welcome",
    title: "Private beta invite",
    description: "Password-protected; the password is in the invitation mail.",
    tagIds: [1],
    startAt: 0.34,
    weight: 6,
    shape: (t) => 0.5 + 0.9 * t,
    channels: { email: 6.0, direct: 1.5 },
    password: DEMO_PASSWORD,
    utm: null,
  },
  {
    id: 8,
    slug: "gh",
    targetUrl: "https://github.com/amargiovanni/margiolink",
    title: "Repository",
    description: "The short link in every talk's last slide.",
    tagIds: [1],
    startAt: 0.02,
    weight: 16,
    shape: (t) => 0.5 + 1.0 * t,
    channels: { social: 1.8, direct: 1.6 },
    utm: null,
  },
  {
    id: 9,
    slug: "changelog",
    targetUrl: "https://github.com/amargiovanni/margiolink/blob/main/CHANGELOG.md",
    title: "Changelog",
    tagIds: [3],
    startAt: 0.11,
    weight: 7,
    shape: (t) => 0.6 + 0.8 * t,
    channels: { direct: 2.0, search: 1.2 },
    utm: null,
  },
  {
    id: 10,
    slug: "talk-slides",
    targetUrl: "https://example.com/slides/privacy-preserving-analytics.pdf",
    title: "Slides — privacy-preserving analytics",
    tagIds: [6, 4],
    startAt: 0.47,
    weight: 7,
    shape: (t) => 0.15 + 2.8 * Math.exp(-t * 10),
    channels: { social: 3.4, direct: 1.2 },
    utm: {
      source: "twitter",
      medium: "social",
      campaign: "devfest-milano",
      content: null,
      term: null,
    },
  },
  {
    id: 11,
    slug: "podcast-ep7",
    targetUrl: "https://example.com/podcast/episode-7",
    title: "Podcast — episode 7",
    tagIds: [4],
    startAt: 0.65,
    weight: 6,
    shape: (t) => 0.2 + 2.4 * Math.exp(-t * 8),
    channels: { social: 4.0, direct: 1.4 },
    mobileBias: 2.4,
    utm: {
      source: "podcast",
      medium: "social",
      campaign: "episode-7",
      content: null,
      term: null,
    },
  },
  {
    id: 12,
    slug: "hiring",
    targetUrl: "https://example.com/jobs/platform-engineer",
    title: "We are hiring a platform engineer",
    tagIds: [4],
    startAt: 0.73,
    weight: 5,
    shape: (t) => 0.4 + 1.6 * Math.exp(-t * 5),
    channels: { social: 3.6, email: 1.4 },
    utm: {
      source: "linkedin",
      medium: "social",
      campaign: "hiring-q4",
      content: null,
      term: null,
    },
  },
  {
    id: 13,
    slug: "roadmap",
    targetUrl: "https://github.com/amargiovanni/margiolink#roadmap",
    title: "Roadmap",
    tagIds: [1, 3],
    startAt: 0.28,
    weight: 5,
    shape: (t) => 0.7 + 0.6 * t,
    channels: { direct: 1.8, search: 1.2 },
    utm: null,
  },
  {
    id: 14,
    slug: "status",
    targetUrl: "https://example.com/status",
    title: "Status page (retired)",
    description: "Switched off when the status page moved; kept for the log.",
    tagIds: [],
    startAt: 0.04,
    weight: 4,
    shape: () => 1,
    channels: { direct: 2.0 },
    // Deactivated inside the window: every click after this day is recorded
    // with outcome `inactive` and answered 410, which is the row the Outcomes
    // panel needs to have something other than `redirect` in it.
    inactiveFrom: 0.78,
    utm: null,
  },
  {
    id: 15,
    slug: "old-landing",
    targetUrl: "https://example.com/old-landing",
    title: "Old landing page",
    description: "Superseded, soft-deleted — visible under the Deleted filter.",
    tagIds: [2],
    startAt: 0,
    weight: 5,
    shape: (t) => 1.4 - 1.0 * t,
    channels: { search: 1.6, direct: 1.4 },
    deletedAt: 0.83,
    utm: null,
  },
  {
    id: 16,
    slug: "sponsor",
    targetUrl: "https://github.com/sponsors/amargiovanni",
    title: "Sponsor the project",
    tagIds: [1, 4],
    startAt: 0.39,
    weight: 4,
    shape: (t) => 0.8 + 0.5 * t,
    channels: { direct: 1.6, social: 1.6 },
    utm: null,
  },
];

/** Weighted pick over `[{weight, ...}]`, with an optional per-item multiplier
 *  so a link can bend a shared pool (more mobile on a QR poster, more email
 *  on a newsletter) without needing a pool of its own. */
function pick(random, pool, multiplier) {
  let total = 0;
  for (const item of pool) total += multiplier ? item.weight * multiplier(item) : item.weight;
  let roll = random() * total;
  for (const item of pool) {
    roll -= multiplier ? item.weight * multiplier(item) : item.weight;
    if (roll <= 0) return item;
  }
  return pool[pool.length - 1];
}

/** 32 hex characters, the same width `visitorHash` in `src/lib/crypto.ts`
 *  produces (an HMAC-SHA-256 truncated to 16 bytes). Not a hash of anything —
 *  see the module comment on what this generator is and is not. */
function fakeHash(random) {
  let out = "";
  for (let i = 0; i < 32; i++) out += "0123456789abcdef"[Math.floor(random() * 16)];
  return out;
}

function utcDay(ts) {
  return new Date(ts * 1000).toISOString().slice(0, 10);
}

/**
 * Build the whole dataset.
 *
 * @param {object} options
 * @param {number} options.now      Unix seconds the window ends at (exclusive-ish: the
 *                                  final day is partial, as a real "today" is).
 * @param {number} [options.days]   Length of the window. The default is
 *                                  `RAW_RETENTION_DAYS`, so the dashboard's
 *                                  longest offered period has both its own
 *                                  span and its comparison window populated.
 * @param {number} [options.seed]   PRNG seed. Change it for a different but
 *                                  equally reproducible dataset.
 */
export function generateDemoData({ now, days = 180, seed = 20260903 } = {}) {
  if (!Number.isFinite(now)) throw new Error("generateDemoData: `now` must be a Unix timestamp");
  if (!Number.isInteger(days) || days < 1)
    throw new Error("generateDemoData: `days` must be a positive integer");

  const random = mulberry32(seed);
  // Midnight UTC of the oldest day in the window, so every day boundary in
  // the output lines up with the boundaries `rollupDay` and the dashboard's
  // date filters use.
  const startOfToday = Math.floor(now / DAY) * DAY;
  const windowStart = startOfToday - (days - 1) * DAY;

  /** A fraction of the window as a day index inside it. `undefined` stays
   *  `undefined` — the difference between "expires on day 128" and "never
   *  expires" has to survive the conversion. */
  const dayOf = (fraction) =>
    fraction === undefined ? undefined : Math.min(days - 1, Math.round(fraction * days));

  const schedule = new Map(
    LINKS.map((link) => [
      link.id,
      {
        start: dayOf(link.startAt) ?? 0,
        expires: dayOf(link.expiresAt),
        inactiveFrom: dayOf(link.inactiveFrom),
        deleted: dayOf(link.deletedAt),
      },
    ]),
  );

  const links = LINKS.map((link) => {
    const when = schedule.get(link.id);
    const createdAt = windowStart + when.start * DAY + Math.floor(random() * DAY);
    return {
      id: link.id,
      slug: link.slug,
      targetUrl: link.targetUrl,
      title: link.title,
      description: link.description ?? null,
      password: link.password ?? null,
      expiresAt: when.expires === undefined ? null : windowStart + when.expires * DAY,
      expiredUrl: link.expiredUrl ?? null,
      isActive: when.inactiveFrom === undefined ? 1 : 0,
      createdAt,
      updatedAt:
        when.inactiveFrom === undefined ? createdAt : windowStart + when.inactiveFrom * DAY,
      deletedAt: when.deleted === undefined ? null : windowStart + when.deleted * DAY,
    };
  });

  const linkTags = LINKS.flatMap((link) =>
    link.tagIds.map((tagId) => ({ linkId: link.id, tagId })),
  );

  const clicks = [];

  for (const link of LINKS) {
    const when = schedule.get(link.id);
    const life = days - when.start;
    // A link soft-deleted mid-window stops collecting the day it happens: a
    // deleted slug 404s before `recordClick` is ever called
    // (`src/routes/redirect.ts`). An expired one keeps recording — it still
    // answers, with outcome `expired` — so only the deleted case truncates.
    const lastDay = when.deleted === undefined ? days : when.deleted;

    for (let day = when.start; day < lastDay; day++) {
      const dayStart = windowStart + day * DAY;
      const weekday = (new Date(dayStart * 1000).getUTCDay() + 6) % 7;
      // Age through the link's own life, 0 at creation and 1 at the end of
      // the window — what `shape` is a function of.
      const age = life <= 1 ? 1 : (day - when.start) / (life - 1);

      const expected =
        link.weight *
        link.shape(age) *
        WEEKDAY_WEIGHTS[weekday] *
        // Site-wide growth: the whole project is bigger in month six than in
        // month one, on top of whatever each link is doing individually.
        (0.55 + 0.9 * (day / days)) *
        // Day-to-day noise, so no two days are the same height.
        (0.72 + 0.56 * random());

      // The last day of the window is "today", and today is only as far
      // through as `now` says it is. Without this the final bar of every
      // chart is a cliff — a full day's traffic recorded by mid-morning.
      const partial = day === days - 1 ? Math.max(0.05, (now - startOfToday) / DAY) : 1;

      const count = Math.max(0, Math.round(expected * partial));
      if (count === 0) continue;

      // Visitors, not clicks: roughly two in three clicks are somebody's
      // first of the day, the rest are the same person coming back. The
      // dashboard's unique count is `COUNT(DISTINCT visitor_hash)` within a
      // day, and a real one is always below the click count.
      const pool = [];
      const poolTarget = Math.max(1, Math.round(count * 0.68));

      for (let i = 0; i < count; i++) {
        const hour = pick(
          random,
          HOUR_WEIGHTS.map((weight, index) => ({ weight, index })),
        ).index;
        const ts = dayStart + hour * 3600 + Math.floor(random() * 3600);
        if (ts >= now) continue;

        const place = pick(random, PLACES);
        const client = pick(random, CLIENTS, (item) =>
          link.mobileBias && item.deviceType === "mobile" ? link.mobileBias : 1,
        );
        const referrer = pick(random, REFERRERS, (item) => link.channels?.[item.type] ?? 1);

        const visitorHash =
          pool.length < poolTarget || random() < 0.5
            ? (() => {
                const fresh = fakeHash(random);
                pool.push(fresh);
                return fresh;
              })()
            : pool[Math.floor(random() * pool.length)];

        // Outcome follows the link's own state at that moment, exactly as the
        // redirect route decides it. An expired link with an `expired_url`
        // still records `expired` — it redirects onward, but not to the
        // original target.
        let outcome = "redirect";
        if (when.inactiveFrom !== undefined && day >= when.inactiveFrom) outcome = "inactive";
        else if (when.expires !== undefined && day >= when.expires) outcome = "expired";
        else if (link.password) {
          const roll = random();
          // Most arrivals see the interstitial; a few get the password wrong;
          // the rest are the same people coming back through with a valid
          // ten-minute cookie.
          outcome =
            roll < 0.58 ? "password_required" : roll < 0.68 ? "password_failed" : "redirect";
        }

        const isBot = client.bot === true;
        // A crawler carries no referrer, no campaign and no language — it is
        // a bare GET. Recording one with a `linkedin.com` referrer would be a
        // row no real crawler ever produces.
        const utm = isBot ? null : link.utm;

        clicks.push({
          linkId: link.id,
          ts,
          visitorHash,
          source: !isBot && link.qrShare && random() < link.qrShare ? "qr" : "link",
          outcome,
          isBot: isBot ? 1 : 0,
          continent: place.continent,
          country: place.country,
          region: place.region,
          city: place.city,
          timezone: place.timezone,
          asnOrg: isBot ? "Google LLC" : place.asnOrg,
          colo: place.colo,
          deviceType: client.deviceType,
          os: client.os,
          osVersion: client.osVersion,
          browser: client.browser,
          browserVersion: client.browserVersion,
          language: isBot ? null : place.language,
          referrerHost: isBot ? null : referrer.host,
          referrerType: isBot ? "direct" : referrer.type,
          utmSource: utm?.source ?? null,
          utmMedium: utm?.medium ?? null,
          utmCampaign: utm?.campaign ?? null,
          utmTerm: null,
          utmContent: null,
        });
      }
    }
  }

  // Chronological, so a `LIMIT`ed read of the raw table during development
  // shows a coherent slice rather than one link's whole history.
  clicks.sort((a, b) => a.ts - b.ts || a.linkId - b.linkId);

  return {
    tags: TAGS,
    links,
    linkTags,
    clicks,
    window: {
      from: windowStart,
      to: now,
      days,
      firstDay: utcDay(windowStart),
      lastDay: utcDay(now),
    },
  };
}
